#!/usr/bin/env bash
# install nginx web server

sudo apt-get update
sudo apt-get install nginx -y

sudo service nginx restar
sudo ufw aloow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo nginx -t

sudo service nginx restart
sudo service nginx reload
