#!/usr/bin/env bash
#parmenent redirection 301

sudo apt-get update
sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html

sfr="server_name _;\n\trewrite ^\/redirect_me https:\/\/youtube.com\/clip\/Ugkx6HbsRfQeUhpclZ_nOS9O-gSOQXosyu2x permanent;"

sudo sed -i "s/server_name _;/$sfr/" /etc/nginx/sites-enabled/default

sudo service nginx restart
