#!/usr/bin/env bash
# not found page

sudo apt-get update
sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html

sfr="server_name _;\n\trewrite ^\/redirect_me https:\/\/youtube.com\/clip\/Ugkx6HbsRfQeUhpclZ_nOS9O-gSOQXosyu2x permanent;"

sudo sed -i "s/server_name _;/$sfr/" /etc/nginx/sites-enabled/default

echo "can't found that page ):" | sudo tee /var/www/html/404.html

sfr="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$sfr/" /etc/nginx/sites-enabled/default

sudo service nginx restart
