#!/usr/bin/env bash
#pings ip address passed ad arg
#Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
#Ping the IP 5 times

if test $# -eq "1"
then
	ping $1 -c 5
else
		echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
