#!/usr/bin/env bash
#fizz Buzz

i=1

while test $i -lt 101
do
	if [ $((i%3)) -eq 0 ] && [ $((i%5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i%5)) -eq 0 ]
		then
			echo "Buzz"
	elif [ $((i%5)) -eq 0 ]
		then
			echo "Fizz"
	else
			echo "$i"
	fi
	i=$(( i + 1 ))
done
