#!/usr/bin/env bash
#print Best School 10 time using while loop

i=1

while test $i -lt 21
do
	echo "$i"
	case "$i" in
		4) echo "bad luck from china"
		;;
		9) echo "bad luck from Japan"
		;;
		17) echo "bad luck from Italy"
		esac
	i=$((i + 1))
done
