#!/usr/bin/env bash
#info about school file
s="school"

if test -e $s
then
	echo "school file exists"
	if test -s $s
		then
			echo "school file is not empty"
		else
			echo "school file is empty"
	fi

	if test -f $s
		then
			echo "school is a regular file"
	fi

else
	echo "school file does not exist"
fi
